server:
  port: 0
spring:
  application:
    name: employee-service-controller
    
management:
  security:
    enabled: false
    
        
  
eureka:
  instance:
    instance-id: ${spring.application.name}:${random.value}
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone : http://127.0.0.1:8761/eureka/
    healthcheck:
      enabled: true


pivotal:
  student:
    name: spring-eureka-client-school-service
  employee:
    name: employee-service-controller
      
      
      
